### ISSUE TITLE
README file not complete

### ISSUE THREAD

**Issue by informatica92** [DavidePastore/gandalf-sax-guy#1]
Hi, 
I just discovered this very interesting repository but I immediately noticed that the README file is empty.
Let me say that an important project like this deserves a more complete README file

**Comment by DavidePastore** [comment]
Hi @informatica92. First, thank you for using this repository. I'll try to improve the README.md file, so anyone could better understand how to use it.

**Comment by informatica92** [comment]
Thanks to you. Finally an easy and complete guide for this very useful package
